"""initial schema

Revision ID: 9d4cf187263a
Revises: 
Create Date: 2026-05-25 15:34:38.527214

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4cf187263a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('address_text', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('address_text')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.String(length=10), nullable=True),
    sa.Column('size_ping', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('room_type', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('pet_allowed', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.Column('internet', sa.Boolean(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('floor', sa.SmallInteger(), nullable=True),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True),
    sa.Column('rental_subsidy', sa.String(length=10), nullable=True),
    sa.Column('water_billing', sa.String(length=20), nullable=True),
    sa.Column('electric_billing', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('contact_method', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_group', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: GeoAlchemy2 auto-creates a spatial index on the location column;
    # explicit create_index omitted to avoid DuplicateTableError.
    op.create_table('raw_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_listing_id', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parsed_listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_posts')
    op.drop_table('listings')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
